name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: install java
      run: sudo apt-get install default-jre
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make migrations
      run: python manage.py makemigrations
    - name: Migrate
      run: python manage.py migrate
    - name: Run server 
      run: gunicorn user_core.wsgi --daemon
    - name: Install playwright
      run: playwright install chromium
    - name: Run Tests
      run: |
        pytest --alluredir=allure_results
    - name: Install allure
      run: npm install -g allure-commandline --save-dev
    - name: Generate allure report
      run: allure generate allure_results/ -o allure_report
    - name: Upload traces
      uses: actions/upload-artifact@v3
      with:
        name: upload_traces
        path: ./traces
    - name: Upload allure
      uses: actions/upload-artifact@v3
      with:
        name: upload_allure
        path: ./allure_report