name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start app
      run: python manage.py makemigrations
          #  python manage.py migrate |
          #  python manage.py runserver |
    - name: Install playwright
      run: playwright install 
    - name: Run Tests
      run: |
        pytest -sv
